### ISSUE TITLE
Can DeeFuzzer do this?

### ISSUE THREAD

**Issue by ghost** [yomguy/DeeFuzzer#85]
I only have very basic needs, but struggling a streaming client to offer them.

- Randomly stream a directory of MP3, no need to transcode
- Notice when new files are added and add them to the random pool
- Optionally offer more a smart shuffle than true random (smart shuffle means everything gets played before things get repeated).

I don't need jingles, this isn't going out over the internet, it's purely streaming a 2000 or so playlist of songs on my local lan.

**Comment by yomguy** [comment]
Hi @mgillespie 
yes, DeeFuzzer should be perfect for your needs ;) It indeed : 
- stream mp3 without transcoding
- checks for new files each time between two track play and add them to the playlist
- read the whole playlist before repeating

there could be just a workaround with the 2nd task because the playlist is entirely re-generated. But we could easily make an exception for this as on option if needed. So please confirm the streaming is OK for you and I will adapt the playlist generator.
